name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
      - name: Install pkg
        run: npm install -g pkg
      - name: Package Node.js project into an executable
        run: pkg package.json
