# Test environment variables on ubuntu-16.04

name: Test

on:
  push:
    branches: [ main ]

jobs:
  test-environment-variables:

    runs-on: ubuntu-16.04

    steps:
      - name: Set environment variables
        run: |
          export TEST_VAR=hello
          echo $TEST_VAR

      - name: show environment variables
        run: |
          echo $PWD
          echo $TEST_VAR
