# Package Node.js project into executable and auto-upload binary release assets

name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        platform: [linux, win, alpine, macos]
        arch: [x64, x86]
        exclude:
          # excludes x86 on linux, alpine and macos
          - arch: x86
            platform: linux
          - arch: x86
            platform: alpine
          - arch: x86
            platform: macos
        include:
          # linux: x64
          - platform: linux
            arch: x64
            artifact_name: AShare
            asset_name: AShare_linux_x64
          # win: x64, x86
          - platform: win
            arch: x64
            artifact_name: AShare.exe
            asset_name: AShare_win_x64
          - platform: win
            arch: x86
            artifact_name: AShare.exe
            asset_name: AShare_win_x86
          # other architectures
          - platform: alpine
            arch: x64
            artifact_name: AShare
            asset_name: AShare_alpine_x64
          - platform: macos
            arch: x64
            artifact_name: AShare
            asset_name: AShare_macos_x64
      fail-fast: false

    env:
      _PLATFORM: ${{ matrix.platform }}
      _ARCH: ${{ matrix.arch }}
      _ARTIFACT_NAME: ${{ matrix.artifact_name }}
      _ASSET_NAME: ${{ matrix.asset_name }}

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Install "zip"
        run: |
          mkdir -p ./zip/{zip-bin,bzip2-bin}
          curl -LOJ http://downloads.sourceforge.net/gnuwin32/zip-3.0-bin.zip --output-dir zip
          curl -LOJ http://downloads.sourceforge.net/gnuwin32/bzip2-1.0.5-bin.zip --output-dir zip
          unzip -q zip/zip*.zip -d zip/zip-bin
          unzip -q zip/bzip2*.zip -d zip/bzip2-bin
          mv zip/zip-bin/bin/zip.exe zip
          mv zip/bzip2-bin/bin/bzip2.dll zip
        shell: bash

      - name: Set environment variables
        run: |
          export PATH=$PATH:$PWD/zip
          echo "PLATFORM=$_PLATFORM" >> $GITHUB_ENV
          echo "ARCH=$_ARCH" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=$_ARTIFACT_NAME" >> $GITHUB_ENV
          echo "ASSET_NAME=$_ASSET_NAME" >> $GITHUB_ENV
        shell: bash

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install
        shell: bash

      - name: Install "pkg"
        run: npm install -g pkg
        shell: bash

      - name: Package Node.js project into an executable (${{ matrix.platform }}_${{ matrix.arch }})
        run: |
          mkdir build_assets
          pkg . -t node14-${{ env.PLATFORM }}-${{ env.ARCH }} --output build_assets/${{ env.ARTIFACT_NAME }}
        shell: bash

      - name: Create archive files
        run: |
          mkdir release
          if [ ${{ env.PLATFORM }} = 'win' ]; then
            zip -j ${{ env.ASSET_NAME }}.zip build_assets/${{ env.ARTIFACT_NAME }}
            mv *.zip release
          else
            tar -zcvf ${{ env.ASSET_NAME }}.tar.gz -C build_assets ${{ env.ARTIFACT_NAME }}
            mv *.tar.gz release
          fi
        shell: bash

      - name: Upload binary files to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ASSET_NAME }}
          path: build_assets/${{ env.ARTIFACT_NAME }}

      - name: Upload binary files to GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: release/${{ env.ASSET_NAME }}.*
          tag: v0.01
          overwrite: true
